ENV['STRIPE_API_KEY'] ||= "59oL1wAB0CbdCJBhZCXkjqsDQHBWFLjr"
ENV['STRIPE_PUBLIC_KEY'] ||= "pk_9JXNDFc04jTTvSL8IVw4XqP9nXrh3"
Stripe.api_key = ENV['STRIPE_API_KEY']
STRIPE_PUBLIC_KEY = ENV['STRIPE_PUBLIC_KEY']